/*!
 * jQuery UI Effects Size 1.12.1
 * http://jqueryui.com
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license.
 * http://jquery.org/license
 */

(function(e){typeof define=="function"&&define.amd?define(["jquery","../version","../effect"],e):e(jQuery)})(function(e){return e.effects.define("size",function(t,n){var r,i,s,o=e(this),u=["fontSize"],a=["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"],f=["borderLeftWidth","borderRightWidth","paddingLeft","paddingRight"],l=t.mode,c=l!=="effect",h=t.scale||"both",p=t.origin||["middle","center"],d=o.css("position"),v=o.position(),m=e.effects.scaledDimensions(o),g=t.from||m,y=t.to||e.effects.scaledDimensions(o,0);e.effects.createPlaceholder(o),l==="show"&&(s=g,g=y,y=s),i={from:{y:g.height/m.height,x:g.width/m.width},to:{y:y.height/m.height,x:y.width/m.width}};if(h==="box"||h==="both")i.from.y!==i.to.y&&(g=e.effects.setTransition(o,a,i.from.y,g),y=e.effects.setTransition(o,a,i.to.y,y)),i.from.x!==i.to.x&&(g=e.effects.setTransition(o,f,i.from.x,g),y=e.effects.setTransition(o,f,i.to.x,y));(h==="content"||h==="both")&&i.from.y!==i.to.y&&(g=e.effects.setTransition(o,u,i.from.y,g),y=e.effects.setTransition(o,u,i.to.y,y)),p&&(r=e.effects.getBaseline(p,m),g.top=(m.outerHeight-g.outerHeight)*r.y+v.top,g.left=(m.outerWidth-g.outerWidth)*r.x+v.left,y.top=(m.outerHeight-y.outerHeight)*r.y+v.top,y.left=(m.outerWidth-y.outerWidth)*r.x+v.left),o.css(g);if(h==="content"||h==="both")a=a.concat(["marginTop","marginBottom"]).concat(u),f=f.concat(["marginLeft","marginRight"]),o.find("*[width]").each(function(){var n=e(this),r=e.effects.scaledDimensions(n),s={height:r.height*i.from.y,width:r.width*i.from.x,outerHeight:r.outerHeight*i.from.y,outerWidth:r.outerWidth*i.from.x},o={height:r.height*i.to.y,width:r.width*i.to.x,outerHeight:r.height*i.to.y,outerWidth:r.width*i.to.x};i.from.y!==i.to.y&&(s=e.effects.setTransition(n,a,i.from.y,s),o=e.effects.setTransition(n,a,i.to.y,o)),i.from.x!==i.to.x&&(s=e.effects.setTransition(n,f,i.from.x,s),o=e.effects.setTransition(n,f,i.to.x,o)),c&&e.effects.saveStyle(n),n.css(s),n.animate(o,t.duration,t.easing,function(){c&&e.effects.restoreStyle(n)})});o.animate(y,{queue:!1,duration:t.duration,easing:t.easing,complete:function(){var t=o.offset();y.opacity===0&&o.css("opacity",g.opacity),c||(o.css("position",d==="static"?"relative":d).offset(t),e.effects.saveStyle(o)),n()}})})});